packages:
  - "apps/frontend"
  - "apps/backend"
  - "apps/admin-portal"
  - "apps/shared"
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
