packages:
  - "apps/frontend"
  - "apps/admin-portal"
  - "apps/mobile-pwa"
  - "apps/shared"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
