<?php

namespace Database\Seeders;

use App\Models\Ticket;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class IncidentSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Ticket::truncate();
        Schema::enableForeignKeyConstraints();

        $demoUser = User::firstOrCreate(
            ['supabase_auth_user_id' => '11111111-1111-1111-1111-111111111111'],
            [
                'name'              => 'LikasLens Demo Citizen',
                'email'             => 'demo@likaslens.ph',
                'password'          => bcrypt('password'),
                'role'              => 'citizen',
                'trust_score'       => 90,
                'reward_points_balance' => 1500,
            ]
        );

        $now = now();

        $tickets = [
            // ── AKLAN (4) ──────────────────────────────────────────────────────
            [
                'title'            => 'Oil Spill Near Boracay Shoreline',
                'status'           => 'investigating',
                'description'      => 'Dark oil slick observed along the western shoreline of Boracay Island near Station 1. Approximately 200 meters of coastline affected. Dead fish and seabirds spotted. Coast Guard notified.',
                'latitude'         => 11.9674,
                'longitude'        => 121.9248,
                'address_text'     => 'Station 1, White Beach, Malay, Aklan',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Coastal Pollution',
                'ai_confidence'    => 0.96,
            ],
            [
                'title'            => 'Mangrove Clearing in Kalibo Wetlands',
                'status'           => 'open',
                'description'      => 'Illegal mangrove clearing operation discovered along the Kalibo River estuary. At least 0.5 hectares of young mangroves have been cut down. Heavy equipment spotted on site.',
                'latitude'         => 11.7077,
                'longitude'        => 122.3643,
                'address_text'     => 'Kalibo River Estuary, Kalibo, Aklan',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.91,
            ],
            [
                'title'            => 'Numancia Landfill Leachate Contamination',
                'status'           => 'monitoring',
                'description'      => 'Leachate from the Numancia municipal landfill has breached containment and is seeping into adjacent farmland. Water samples collected show elevated heavy metal levels.',
                'latitude'         => 11.7180,
                'longitude'        => 122.3300,
                'address_text'     => 'Municipal Landfill, Numancia, Aklan',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Waste Management',
                'ai_confidence'    => 0.88,
            ],
            [
                'title'            => 'Coral Bleaching at Boracay Marine Sanctuary',
                'status'           => 'open',
                'description'      => 'Significant coral bleaching event observed at the Boracay Marine Sanctuary dive site. Estimated 40% of coral cover affected. Water temperatures recorded at 2°C above normal for the season.',
                'latitude'         => 11.9590,
                'longitude'        => 121.9300,
                'address_text'     => 'Boracay Marine Sanctuary, Malay, Aklan',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Coastal Pollution',
                'ai_confidence'    => 0.94,
            ],

            // ── ANTIQUE (4) ────────────────────────────────────────────────────
            [
                'title'            => 'Sibalom Forest Illegal Logging Operation',
                'status'           => 'investigating',
                'description'      => 'Reports of unauthorized chainsaw operations within the Sibalom Natural Park buffer zone. Several old-growth Narra trees have been felled. DENR rangers deployed to assess damage.',
                'latitude'         => 10.7900,
                'longitude'        => 122.0170,
                'address_text'     => 'Sibalom Natural Park, Sibalom, Antique',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Forestry Violation',
                'ai_confidence'    => 0.97,
            ],
            [
                'title'            => 'Fish Kill in San Jose Coastal Waters',
                'status'           => 'open',
                'description'      => 'Mass fish kill reported along a 3-kilometer stretch of coastline near San Jose. Local fishermen suspect toxic algal bloom or industrial discharge from nearby processing plant.',
                'latitude'         => 10.7440,
                'longitude'        => 121.9435,
                'address_text'     => 'Barangay Funda-Dalipe Coastal, San Jose, Antique',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.93,
            ],
            [
                'title'            => 'Hamtic River Sedimentation Crisis',
                'status'           => 'monitoring',
                'description'      => 'Excessive siltation in the Hamtic River due to upstream quarry activities. River water has turned muddy brown affecting irrigation for 200+ hectares of rice paddies.',
                'latitude'         => 10.7050,
                'longitude'        => 121.9800,
                'address_text'     => 'Hamtic River Bridge, Hamtic, Antique',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.85,
            ],
            [
                'title'            => 'Culasi Marine Turtle Nesting Site Disturbance',
                'status'           => 'open',
                'description'      => 'Marine turtle nesting site at Culasi beach disrupted by unauthorized beachfront construction. Freshly laid turtle eggs found crushed. Nesting season is currently active.',
                'latitude'         => 11.4260,
                'longitude'        => 122.0550,
                'address_text'     => 'Barangay Malalison Beach, Culasi, Antique',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.92,
            ],

            // ── CAPIZ (4) ──────────────────────────────────────────────────────
            [
                'title'            => 'Roxas City Fish Port Waste Discharge',
                'status'           => 'open',
                'description'      => 'Untreated fish processing waste and bloodwater being discharged directly into the sea from the Roxas City fish port complex. Strong odor complaints from nearby residents.',
                'latitude'         => 11.5853,
                'longitude'        => 122.7511,
                'address_text'     => 'Roxas City Fish Port, Roxas City, Capiz',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.89,
            ],
            [
                'title'            => 'Panay Riverbank Collapse',
                'status'           => 'resolved',
                'description'      => 'A 50-meter section of the Panay River riverbank collapsed due to heavy monsoon rains and erosion. DPWH has completed rehabilitation and slope stabilization works.',
                'latitude'         => 11.5560,
                'longitude'        => 122.7920,
                'address_text'     => 'Panay River, Panay, Capiz',
                'urgency_score'    => 2,
                'ai_triage_summary' => 'Land Use',
                'ai_confidence'    => 0.95,
                'resolved_at'      => '2026-05-15 10:30:00',
            ],
            [
                'title'            => 'Pontevedra Sugarcane Field Burning',
                'status'           => 'open',
                'description'      => 'Widespread sugarcane field burning observed across Pontevedra during harvest season. Air quality index has reached hazardous levels. Nearby schools have suspended classes.',
                'latitude'         => 11.4830,
                'longitude'        => 122.8350,
                'address_text'     => 'Barangay San Juan Farmlands, Pontevedra, Capiz',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.87,
            ],
            [
                'title'            => 'Dao Wetland Encroachment',
                'status'           => 'investigating',
                'description'      => 'Portions of the Dao municipal wetland have been illegally filled and converted to fishponds. Migratory bird populations have noticeably declined in the area.',
                'latitude'         => 11.3950,
                'longitude'        => 122.6850,
                'address_text'     => 'Dao Wetland Conservation Area, Dao, Capiz',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.90,
            ],

            // ── GUIMARAS (4) ───────────────────────────────────────────────────
            [
                'title'            => 'Jordan Marine Protected Area Boundary Dispute',
                'status'           => 'open',
                'description'      => 'Commercial fishing vessels repeatedly encroaching into the Jordan Marine Protected Area. Local bantay dagat volunteers report inadequate enforcement resources.',
                'latitude'         => 10.6598,
                'longitude'        => 122.5959,
                'address_text'     => 'Jordan MPA, Jordan, Guimaras',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Coastal Pollution',
                'ai_confidence'    => 0.86,
            ],
            [
                'title'            => 'Buenavista Open Dumpsite Fire',
                'status'           => 'resolved',
                'description'      => 'Spontaneous combustion fire at the Buenavista open dumpsite burned for 3 days, releasing toxic smoke over residential areas. Fire fully extinguished by BFP. Site now cordoned off.',
                'latitude'         => 10.7030,
                'longitude'        => 122.6270,
                'address_text'     => 'Municipal Dumpsite, Buenavista, Guimaras',
                'urgency_score'    => 2,
                'ai_triage_summary' => 'Waste Management',
                'ai_confidence'    => 0.91,
                'resolved_at'      => '2026-05-12 08:00:00',
            ],
            [
                'title'            => 'Nueva Valencia Sea Grass Degradation',
                'status'           => 'monitoring',
                'description'      => 'Sea grass beds in Nueva Valencia showing signs of significant degradation. Decline linked to increased boat traffic and anchor damage from tourism activities.',
                'latitude'         => 10.5150,
                'longitude'        => 122.5400,
                'address_text'     => 'Tando Island Waters, Nueva Valencia, Guimaras',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Coastal Pollution',
                'ai_confidence'    => 0.83,
            ],
            [
                'title'            => 'San Lorenzo Mining Exploration Permit Concern',
                'status'           => 'open',
                'description'      => 'Mining exploration permit application filed covering 500 hectares in San Lorenzo. Local communities and the diocese have expressed strong opposition. Public hearing scheduled.',
                'latitude'         => 10.6450,
                'longitude'        => 122.6100,
                'address_text'     => 'Barangay Cabano, San Lorenzo, Guimaras',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Land Use',
                'ai_confidence'    => 0.88,
            ],

            // ── ILOILO (5) ─────────────────────────────────────────────────────
            [
                'title'            => 'Iloilo River Domestic Waste Pollution',
                'status'           => 'monitoring',
                'description'      => 'Elevated fecal coliform levels detected in Iloilo River water samples. Source traced to informal settlements along the riverbank lacking proper sanitation facilities.',
                'latitude'         => 10.7202,
                'longitude'        => 122.5621,
                'address_text'     => 'Iloilo River, near Molo Bridge, Iloilo City',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.92,
            ],
            [
                'title'            => 'Dingle Watershed Flash Flood Damage',
                'status'           => 'resolved',
                'description'      => 'Flash flood caused by deforestation in the upper Dingle watershed damaged 30 homes and 3 irrigation canals. Relief operations completed. Reforestation plan proposed.',
                'latitude'         => 10.9975,
                'longitude'        => 122.6717,
                'address_text'     => 'Barangay Lumboy, Dingle, Iloilo',
                'urgency_score'    => 2,
                'ai_triage_summary' => 'Environmental Hazard',
                'ai_confidence'    => 0.93,
                'resolved_at'      => '2026-05-10 16:00:00',
            ],
            [
                'title'            => 'Miagao Coastal Road Construction Erosion',
                'status'           => 'open',
                'description'      => 'Ongoing coastal road construction in Miagao has caused severe hillside erosion. Landslides reported during heavy rains. Road debris entering marine habitat.',
                'latitude'         => 10.6442,
                'longitude'        => 122.2352,
                'address_text'     => 'Coastal Road Project, Miagao, Iloilo',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Land Use',
                'ai_confidence'    => 0.90,
            ],
            [
                'title'            => 'Oton Shoreline Plastic Accumulation',
                'status'           => 'open',
                'description'      => 'Massive accumulation of plastic debris along the Oton shoreline following recent typhoon. Community cleanup drive organized but overwhelmed by volume. Estimated 5 tons collected so far.',
                'latitude'         => 10.6930,
                'longitude'        => 122.4740,
                'address_text'     => 'Barangay Trapiche Shoreline, Oton, Iloilo',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Waste Management',
                'ai_confidence'    => 0.84,
            ],
            [
                'title'            => 'Leganes Fish Pen Water Quality Decline',
                'status'           => 'monitoring',
                'description'      => 'Dissolved oxygen levels in Leganes fish pen area dropping below critical threshold. Possible cause: accumulated fish feed waste and reduced water circulation.',
                'latitude'         => 10.7380,
                'longitude'        => 122.5750,
                'address_text'     => 'Leganes Fish Pen Complex, Leganes, Iloilo',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.86,
            ],

            // ── NEGROS OCCIDENTAL (5) ─────────────────────────────────────────
            [
                'title'            => 'Bacolod Smog Alert: Cane Field Burning',
                'status'           => 'open',
                'description'      => 'Air quality index in Bacolod City reached hazardous levels due to widespread sugar cane field burning in surrounding agricultural areas. Respiratory cases in hospitals up 40% this week.',
                'latitude'         => 10.6713,
                'longitude'        => 122.9511,
                'address_text'     => 'Bacolod City Metro, Negros Occidental',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.94,
            ],
            [
                'title'            => 'Silay Northern Negros Natural Park Poaching',
                'status'           => 'investigating',
                'description'      => 'Suspected poaching activity inside the Northern Negros Natural Park near Silay. Traps and snares discovered. Critically endangered Visayan warty pig and Negros bleeding-heart pigeon at risk.',
                'latitude'         => 10.8000,
                'longitude'        => 123.0000,
                'address_text'     => 'NNNP - Patag Sector, Silay, Negros Occidental',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.95,
            ],
            [
                'title'            => 'Victorias Sugar Mill Wastewater Spill',
                'status'           => 'investigating',
                'description'      => 'Untreated molasses wastewater from the Victorias sugar mill overflowed into the Malihao River. Water has turned dark brown and strong foul odor reported for 5 kilometers downstream.',
                'latitude'         => 10.9000,
                'longitude'        => 123.0700,
                'address_text'     => 'Malihao River, Victorias, Negros Occidental',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.97,
            ],
            [
                'title'            => 'Bago City Irrigation Dam Siltation',
                'status'           => 'monitoring',
                'description'      => 'Bago River irrigation dam experiencing accelerated siltation, reducing water storage capacity by an estimated 15%. Threatens irrigation supply for 5,000 hectares of farmland.',
                'latitude'         => 10.5400,
                'longitude'        => 122.8400,
                'address_text'     => 'Bago Irrigation Dam, Bago, Negros Occidental',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.89,
            ],
            [
                'title'            => 'Sipalay Mine Tailings Dam Integrity Concern',
                'status'           => 'open',
                'description'      => 'Structural cracks observed in the secondary tailings dam at the Sipalay mining complex. Heavy rainfall forecast for the coming week. Evacuation advisories issued for downstream communities.',
                'latitude'         => 9.7510,
                'longitude'        => 122.4000,
                'address_text'     => 'Sipalay Mining Complex, Sipalay, Negros Occidental',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Environmental Hazard',
                'ai_confidence'    => 0.96,
            ],

            // ── CROSS-REGIONAL ──────────────────────────────────────────────────
            [
                'title'            => 'Guimaras-Iloilo Ferry Oil Leak',
                'status'           => 'resolved',
                'description'      => 'Minor fuel leak from a ferry vessel in the Guimaras-Iloilo Strait. PCG deployed oil spill booms within 2 hours. Leak contained. Environmental impact assessment shows minimal damage.',
                'latitude'         => 10.6300,
                'longitude'        => 122.5800,
                'address_text'     => 'Guimaras-Iloilo Strait, Panay Gulf',
                'urgency_score'    => 2,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.90,
                'resolved_at'      => '2026-05-08 14:00:00',
            ],

            // ── VIETNAM (6) ───────────────────────────────────────────────────
            [
                'title'            => 'Ha Long Bay Limestone Erosion from Tourism',
                'status'           => 'investigating',
                'description'      => 'Accelerated erosion of limestone karst formations in Ha Long Bay attributed to increased cruise ship traffic and wave action. UNESCO heritage site at risk.',
                'latitude'         => 20.9101,
                'longitude'        => 107.1839,
                'address_text'     => 'Ha Long Bay, Quang Ninh Province, Vietnam',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Land Use',
                'ai_confidence'    => 0.94,
            ],
            [
                'title'            => 'Mekong Delta Saltwater Intrusion',
                'status'           => 'open',
                'description'      => 'Severe saltwater intrusion in the Mekong Delta has rendered 12,000 hectares of rice paddies uncultivable. Worst intrusion in 5 years linked to upstream dam operations and sea level rise.',
                'latitude'         => 9.7489,
                'longitude'        => 106.2325,
                'address_text'     => 'An Giang Province, Mekong Delta, Vietnam',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.96,
            ],
            [
                'title'            => 'Da Nang Coastal Construction Wetland Filling',
                'status'           => 'open',
                'description'      => 'Illegal filling of protected coastal wetlands for resort development in Da Nang. Mangrove buffer zone reduced by 40%. Migratory bird habitat severely impacted.',
                'latitude'         => 16.0544,
                'longitude'        => 108.2022,
                'address_text'     => 'Ngu Hanh Son District, Da Nang, Vietnam',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.91,
            ],
            [
                'title'            => 'Ho Chi Minh City Industrial Waste Dumping',
                'status'           => 'monitoring',
                'description'      => 'Chemical waste drums discovered dumped in a canal in Binh Tan District. Suspected from a nearby industrial zone. Water testing reveals elevated heavy metals.',
                'latitude'         => 10.7681,
                'longitude'        => 106.6237,
                'address_text'     => 'Binh Tan District, Ho Chi Minh City, Vietnam',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.89,
            ],
            [
                'title'            => 'Phu Quoc Coral Reef Anchoring Damage',
                'status'           => 'resolved',
                'description'      => 'Extensive coral damage from illegal anchor drops at Phu Quoc marine tourism site. 30% of reef flat affected. Mooring buoys now installed. Recovery monitoring underway.',
                'latitude'         => 10.2270,
                'longitude'        => 103.9635,
                'address_text'     => 'Phu Quoc Island, Kien Giang, Vietnam',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Coastal Pollution',
                'ai_confidence'    => 0.92,
                'resolved_at'      => '2026-04-20 09:00:00',
            ],
            [
                'title'            => 'Hanoi Air Quality Emergency',
                'status'           => 'open',
                'description'      => 'AQI levels in Hanoi exceeded 300 (hazardous) for 5 consecutive days. Coal-fired power plants and vehicle emissions identified as primary sources. Schools closed.',
                'latitude'         => 21.0285,
                'longitude'        => 105.8542,
                'address_text'     => 'Hoan Kiem District, Hanoi, Vietnam',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.97,
            ],

            // ── INDONESIA (6) ─────────────────────────────────────────────────
            [
                'title'            => 'Jakarta North Coast Land Subsidence',
                'status'           => 'open',
                'description'      => 'Coastal areas of North Jakarta sinking at 15cm per year. Seawalls failing. 500,000 residents at risk. Giant Sea Wall project stalled due to funding.',
                'latitude'         => -6.1219,
                'longitude'        => 106.8447,
                'address_text'     => 'North Jakarta Coastal Zone, DKI Jakarta, Indonesia',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Environmental Hazard',
                'ai_confidence'    => 0.98,
            ],
            [
                'title'            => 'Bali Beach Plastic Pollution Crisis',
                'status'           => 'investigating',
                'description'      => 'Kuta and Seminyak beaches buried under 2 meters of plastic debris after seasonal currents shifted. Tourism industry severely impacted. International cleanup volunteers deployed.',
                'latitude'         => -8.7180,
                'longitude'        => 115.1689,
                'address_text'     => 'Kuta Beach, Bali, Indonesia',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Waste Management',
                'ai_confidence'    => 0.95,
            ],
            [
                'title'            => 'Borneo Peatland Fire Emergency',
                'status'           => 'open',
                'description'      => 'Massive peatland fires in Central Kalimantan producing transboundary haze. Air quality in 3 provinces at hazardous levels. Military deployed for water bombing.',
                'latitude'         => -2.2168,
                'longitude'        => 114.4021,
                'address_text'     => 'Central Kalimantan, Indonesian Borneo',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.97,
            ],
            [
                'title'            => 'Baliem River Mining Pollution',
                'status'           => 'monitoring',
                'description'      => 'Artisanal gold mining operations in Papua contaminating the Baliem River with mercury. Fish populations declining. Indigenous communities report health concerns.',
                'latitude'         => -4.0667,
                'longitude'        => 138.8833,
                'address_text'     => 'Baliem Valley, Jayawijaya, Papua, Indonesia',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.88,
            ],
            [
                'title'            => 'Surabaya River Eutrophication',
                'status'           => 'investigating',
                'description'      => 'Massive algal bloom in Surabaya River causing fish kills and drinking water supply disruption for 200,000 residents. Agricultural runoff identified as primary cause.',
                'latitude'         => -7.2575,
                'longitude'        => 112.7521,
                'address_text'     => 'Surabaya River, East Java, Indonesia',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.91,
            ],
            [
                'title'            => 'Riau Forest Fire Haze',
                'status'           => 'resolved',
                'description'      => 'Peatland fires in Riau Province extinguished after 3-week emergency response. 15,000 hectares burned. Haze dispersed. Reforestation program initiated.',
                'latitude'         => 0.2936,
                'longitude'        => 101.4238,
                'address_text'     => 'Riau Province, Sumatra, Indonesia',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.93,
                'resolved_at'      => '2026-03-15 12:00:00',
            ],

            // ── THAILAND (4) ──────────────────────────────────────────────────
            [
                'title'            => 'Bangkok PM2.5 Air Quality Crisis',
                'status'           => 'open',
                'description'      => 'PM2.5 levels in Bangkok exceeding WHO guidelines by 8x. Crop burning in northern provinces and vehicle emissions creating toxic smog. Health emergency declared.',
                'latitude'         => 13.7563,
                'longitude'        => 100.5018,
                'address_text'     => 'Bangkok Metropolitan, Thailand',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.96,
            ],
            [
                'title'            => 'Phuket Coral Bleaching Event',
                'status'           => 'open',
                'description'      => 'Severe coral bleaching at Phi Phi Islands marine national park. Water temperatures 3°C above seasonal average. 60% of hard coral showing bleaching symptoms.',
                'latitude'         => 7.7407,
                'longitude'        => 98.7784,
                'address_text'     => 'Phi Phi Islands, Krabi, Thailand',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Coastal Pollution',
                'ai_confidence'    => 0.94,
            ],
            [
                'title'            => 'Chao Phraya River Microplastic Contamination',
                'status'           => 'investigating',
                'description'      => 'Microplastic concentration in the Chao Phraya River measured at 12,000 particles per cubic meter. Highest recorded in Southeast Asia. Affects Bangkok drinking water intake.',
                'latitude'         => 13.7420,
                'longitude'        => 100.5010,
                'address_text'     => 'Chao Phraya River, Bangkok, Thailand',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.90,
            ],
            [
                'title'            => 'Andaman Sea Illegal Fishing Trawlers',
                'status'           => 'resolved',
                'description'      => 'Thai navy intercepted 8 illegal bottom trawlers in the Andaman Sea marine protected area. Gear and catch confiscated. 50km of seabed habitat damaged.',
                'latitude'         => 7.8804,
                'longitude'        => 98.3923,
                'address_text'     => 'Andaman Sea MPA, Phang Nga, Thailand',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.93,
                'resolved_at'      => '2026-04-01 10:00:00',
            ],

            // ── MALAYSIA (4) ──────────────────────────────────────────────────
            [
                'title'            => 'Klang Valley River Chemical Spill',
                'status'           => 'investigating',
                'description'      => 'Chemical spill from a factory in Shah Alam contaminated the Klang River. 20km stretch affected. Water supply to 500,000 residents disrupted. DOE investigating.',
                'latitude'         => 3.0733,
                'longitude'        => 101.5185,
                'address_text'     => 'Klang River, Shah Alam, Selangor, Malaysia',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Pollution',
                'ai_confidence'    => 0.95,
            ],
            [
                'title'            => 'Borneo Deforestation for Palm Oil',
                'status'           => 'open',
                'description'      => '2,000 hectares of primary rainforest in Sabah cleared for palm oil plantation. Orangutan habitat fragmented. WWF monitoring population displacement.',
                'latitude'         => 5.9804,
                'longitude'        => 116.0735,
                'address_text'     => 'Kinabatangan District, Sabah, Malaysian Borneo',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Forestry Violation',
                'ai_confidence'    => 0.96,
            ],
            [
                'title'            => 'Penang Coastal Reclamation Impact',
                'status'           => 'monitoring',
                'description'      => 'Coastal reclamation for the Penang South Islands project affecting 4,000 acres of fishing grounds. Fishermen report 60% decline in catch. EIA under review.',
                'latitude'         => 5.2421,
                'longitude'        => 100.2586,
                'address_text'     => 'South Penang Coast, Penang, Malaysia',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Land Use',
                'ai_confidence'    => 0.89,
            ],
            [
                'title'            => 'Johor Bahru Landfill Gas Emission',
                'status'           => 'open',
                'description'      => 'Uncontrolled methane emissions from the Pasir Gudang landfill threatening nearby residential areas. Explosive gas levels detected. Evacuation of 200 households ordered.',
                'latitude'         => 1.4854,
                'longitude'        => 103.8661,
                'address_text'     => 'Pasir Gudang Landfill, Johor, Malaysia',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Environmental Hazard',
                'ai_confidence'    => 0.93,
            ],

            // ── MYANMAR (3) ───────────────────────────────────────────────────
            [
                'title'            => 'Ayeyarwady River Plastic Choke Point',
                'status'           => 'open',
                'description'      => 'Massive plastic debris accumulation at Bago River confluence blocking Ayeyarwady navigation channel. Fishing communities report fish stock collapse.',
                'latitude'         => 16.8714,
                'longitude'        => 96.2037,
                'address_text'     => 'Bago River Confluence, Yangon Region, Myanmar',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Waste Management',
                'ai_confidence'    => 0.87,
            ],
            [
                'title'            => 'Shan State Illegal Jade Mining',
                'status'           => 'open',
                'description'      => 'Unregulated jade mining operations in Hpakant causing catastrophic landslides. 12 miners buried. Toxic tailings entering the Uru River. Community in crisis.',
                'latitude'         => 25.9500,
                'longitude'        => 96.3500,
                'address_text'     => 'Hpakant, Kachin State, Myanmar',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Environmental Hazard',
                'ai_confidence'    => 0.94,
            ],
            [
                'title'            => 'Tanintharyi Mangrove Destruction',
                'status'           => 'investigating',
                'description'      => 'Large-scale mangrove clearing for shrimp farm expansion in Tanintharyi Region. 800 hectares affected. Critical coastal buffer zone lost.',
                'latitude'         => 14.0833,
                'longitude'        => 98.2000,
                'address_text'     => 'Tanintharyi Coast, Tanintharyi Region, Myanmar',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.91,
            ],

            // ── CAMBODIA (2) ──────────────────────────────────────────────────
            [
                'title'            => 'Tonle Sap Lake Water Level Crisis',
                'status'           => 'open',
                'description'      => 'Tonle Sap Lake at record low water level for dry season. Fishing communities displaced. Hydropower dams upstream blamed for disrupting natural flood pulse.',
                'latitude'         => 12.8000,
                'longitude'        => 104.0000,
                'address_text'     => 'Tonle Sap Lake, Cambodia',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Water Quality',
                'ai_confidence'    => 0.95,
            ],
            [
                'title'            => 'Preah Vihear Temple Forest Encroachment',
                'status'           => 'investigating',
                'description'      => 'Illegal logging and land encroachment in the Preah Vihear temple World Heritage buffer zone. Ancient forest cleared for farmland.',
                'latitude'         => 14.3919,
                'longitude'        => 104.6794,
                'address_text'     => 'Preah Vihear Province, Cambodia',
                'urgency_score'    => 4,
                'ai_triage_summary' => 'Forestry Violation',
                'ai_confidence'    => 0.90,
            ],

            // ── LAOS (2) ──────────────────────────────────────────────────────
            [
                'title'            => 'Mekong Mainstream Dam Fish Migration Block',
                'status'           => 'open',
                'description'      => 'Don Sahong Dam fish passage inadequate. Mekong giant carp and Irrawaddy dolphin populations declining. 11 million people depend on Mekong fisheries.',
                'latitude'         => 14.3333,
                'longitude'        => 105.8333,
                'address_text'     => 'Don Sahong, Champasak Province, Laos',
                'urgency_score'    => 5,
                'ai_triage_summary' => 'Wildlife Protection',
                'ai_confidence'    => 0.93,
            ],
            [
                'title'            => 'Vientiane Urban Air Quality Decline',
                'status'           => 'monitoring',
                'description'      => 'Seasonal burning and vehicle emissions causing AQI to spike in Vientiane. Neighboring countries contributing to transboundary haze.',
                'latitude'         => 17.9757,
                'longitude'        => 102.6331,
                'address_text'     => 'Vientiane Capital, Laos',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.86,
            ],

            // ── SINGAPORE (1) ─────────────────────────────────────────────────
            [
                'title'            => 'Singapore Haze Episode Monitoring',
                'status'           => 'monitoring',
                'description'      => 'PSI levels reaching 150+ due to Indonesian peatland fires. NEA monitoring air quality across the island. Vulnerable groups advised to stay indoors.',
                'latitude'         => 1.3521,
                'longitude'        => 103.8198,
                'address_text'     => 'Nationwide, Singapore',
                'urgency_score'    => 3,
                'ai_triage_summary' => 'Air Quality',
                'ai_confidence'    => 0.92,
            ],

            // ── BRUNEI (1) ────────────────────────────────────────────────────
            [
                'title'            => 'Temburong Rainforest Canopy Research Station',
                'status'           => 'resolved',
                'description'      => 'Illegal clearing near Temburong research station stopped. 50 hectares of pristine primary forest saved. Enforcement action completed.',
                'latitude'         => 4.5833,
                'longitude'        => 115.1333,
                'address_text'     => 'Temburong District, Brunei',
                'urgency_score'    => 2,
                'ai_triage_summary' => 'Forestry Violation',
                'ai_confidence'    => 0.91,
                'resolved_at'      => '2026-04-10 16:00:00',
            ],
        ];

        foreach ($tickets as $data) {
            Ticket::create(array_merge(
                ['id' => (string) Str::uuid()],
                [
                'reporter_user_id'  => $demoUser->id,
                'status'            => $data['status'],
                'title'             => $data['title'],
                'description'       => $data['description'],
                'latitude'          => $data['latitude'],
                'longitude'         => $data['longitude'],
                'address_text'      => $data['address_text'],
                'urgency_score'     => $data['urgency_score'],
                'ai_triage_summary' => $data['ai_triage_summary'],
                'ai_confidence'     => $data['ai_confidence'],
                'resolved_at'       => $data['resolved_at'] ?? null,
                'created_at'        => $now->copy()->subDays(rand(1, 150)),
                'updated_at'        => $now,
            ]));
        }
    }
}
