<?php

namespace Database\Seeders;

use App\Models\NgoGroup;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class NgoSeeder extends Seeder
{
    public function run(): void
    {
        NgoGroup::truncate();

        $now = now();

        $ngos = [
            // ── AKLAN ──────────────────────────────────────────────────────────
            [
                'name'              => 'Kalibo Mangrove Restoration Initiative',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Aklan',
                'city_municipality' => 'Kalibo',
                'contact_email'     => 'kmri@aklanenviro.org.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 268 1123',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Boracay Coastal Guardians',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Aklan',
                'city_municipality' => 'Malay',
                'contact_email'     => 'guardians@boracayeco.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 288 4456',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Numancia Solid Waste Management Council',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Aklan',
                'city_municipality' => 'Numancia',
                'contact_email'     => 'nswmc@numancia-aklan.gov.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 273 9901',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Aklan River Basin Protectors',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Aklan',
                'city_municipality' => 'New Washington',
                'contact_email'     => 'arbp@aklanwatershed.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 265 3378',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Ibajay Wildlife Conservation Society',
                'focus_area'        => 'Wildlife Protection',
                'region'            => 'Region VI',
                'province'          => 'Aklan',
                'city_municipality' => 'Ibajay',
                'contact_email'     => 'iwcs@ibajaygreen.org.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 289 6521',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── ANTIQUE ───────────────────────────────────────────────────────
            [
                'name'              => 'San Jose Marine Sanctuary Alliance',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Antique',
                'city_municipality' => 'San Jose',
                'contact_email'     => 'sjmsa@antiquemarine.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 540 8123',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Sibalom Reforestation Project',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Antique',
                'city_municipality' => 'Sibalom',
                'contact_email'     => 'srp@sibalomforest.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 541 2456',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Hamtic River Cleanup Brigade',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Antique',
                'city_municipality' => 'Hamtic',
                'contact_email'     => 'hrcb@hamticenviro.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 542 3890',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Culasi Eco-Tourism Stewards',
                'focus_area'        => 'Wildlife Protection',
                'region'            => 'Region VI',
                'province'          => 'Antique',
                'city_municipality' => 'Culasi',
                'contact_email'     => 'cets@culasigreen.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 543 7714',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Patnongon Environmental Watch',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Antique',
                'city_municipality' => 'Patnongon',
                'contact_email'     => 'pew@patnongoneco.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 544 1023',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── CAPIZ ─────────────────────────────────────────────────────────
            [
                'name'              => 'Roxas City Coastal Sustainability Network',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Capiz',
                'city_municipality' => 'Roxas City',
                'contact_email'     => 'rccsn@roxascitygreen.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 621 3344',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Panay River Guardians',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Capiz',
                'city_municipality' => 'Panay',
                'contact_email'     => 'prg@panayriver.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 622 8765',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Pontevedra Zero-Waste Coalition',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Capiz',
                'city_municipality' => 'Pontevedra',
                'contact_email'     => 'pzwc@pontevedraeco.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 623 5410',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Mambusao Agroforestry Collective',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Capiz',
                'city_municipality' => 'Mambusao',
                'contact_email'     => 'mac@mambusaoforest.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 624 2987',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Dao Wetland Preservation Society',
                'focus_area'        => 'Wildlife Protection',
                'region'            => 'Region VI',
                'province'          => 'Capiz',
                'city_municipality' => 'Dao',
                'contact_email'     => 'dwps@daowetland.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 36 625 4332',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── GUIMARAS ──────────────────────────────────────────────────────
            [
                'name'              => 'Jordan Marine Protected Area Council',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Guimaras',
                'city_municipality' => 'Jordan',
                'contact_email'     => 'jmpac@jordan-guimaras.gov.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 581 7712',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Buenavista Solid Waste Task Force',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Guimaras',
                'city_municipality' => 'Buenavista',
                'contact_email'     => 'bswtf@buenavistaclean.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 582 3409',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Nueva Valencia Mangrove Watch',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Guimaras',
                'city_municipality' => 'Nueva Valencia',
                'contact_email'     => 'nvmw@nuevavalencia.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 583 1892',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Sibunag Greenbelt Alliance',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Guimaras',
                'city_municipality' => 'Sibunag',
                'contact_email'     => 'sga@sibunagforest.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 584 6534',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'San Lorenzo Coastal Rangers',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Guimaras',
                'city_municipality' => 'San Lorenzo',
                'contact_email'     => 'slcr@sanlorenzo.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 585 8715',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── ILOILO ────────────────────────────────────────────────────────
            [
                'name'              => 'Iloilo City Environmental Defense League',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Iloilo City',
                'contact_email'     => 'icedl@iloilocitygreen.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 337 2210',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Dingle Waste Management Coalition',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Dingle',
                'contact_email'     => 'dwmc@dingle-iloilo.gov.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 338 4523',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Miagao Hills Reforestation Corps',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Miagao',
                'contact_email'     => 'mhrc@miagaogreen.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 339 7834',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Oton Shoreline Protectors',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Oton',
                'contact_email'     => 'osp@otonshoreline.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 340 1198',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Pototan Agro-Ecology Network',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Pototan',
                'contact_email'     => 'paen@pototanagri.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 341 5672',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Passi City Biodiversity Council',
                'focus_area'        => 'Wildlife Protection',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Passi City',
                'contact_email'     => 'pcbc@passicity.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 342 9054',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Leganes Riverine Ecosystem Trust',
                'focus_area'        => 'Wildlife Protection',
                'region'            => 'Region VI',
                'province'          => 'Iloilo',
                'city_municipality' => 'Leganes',
                'contact_email'     => 'lret@leganesriver.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 33 343 2310',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── NEGROS OCCIDENTAL ─────────────────────────────────────────────
            [
                'name'              => 'Bacolod Urban Greening Initiative',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'Bacolod City',
                'contact_email'     => 'bugi@bacolodenviro.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 433 8012',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Silay Heritage Forest Keepers',
                'focus_area'        => 'Wildlife Protection',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'Silay',
                'contact_email'     => 'shfk@silayforest.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 434 2456',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Victorias Coastal Cleanup Movement',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'Victorias',
                'contact_email'     => 'vccm@victoriasgreen.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 435 9803',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Bago Watershed Restoration Alliance',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'Bago',
                'contact_email'     => 'bwra@bagowatershed.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 436 6512',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'La Carlota Solid Waste Alliance',
                'focus_area'        => 'Solid Waste',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'La Carlota',
                'contact_email'     => 'lcswa@lacarlotaclean.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 437 3410',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Kabankalan Eco-Warriors Collective',
                'focus_area'        => 'Reforestation',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'Kabankalan',
                'contact_email'     => 'kewc@kabankalaneco.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 438 1245',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => 'Sipalay Marine Biodiversity Project',
                'focus_area'        => 'Coastal Cleanup',
                'region'            => 'Region VI',
                'province'          => 'Negros Occidental',
                'city_municipality' => 'Sipalay',
                'contact_email'     => 'smbp@sipalaymarine.ph',
                'contact_phone'     => null,
                'contact_number'    => '+63 34 439 8923',
                'is_active'         => true,
                'is_verified'       => true,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        $ngos = array_map(fn($ngo) => array_merge(['id' => (string) Str::uuid()], $ngo), $ngos);

        // Strip columns that don't yet exist (migration may not have run)
        $existingColumns = Schema::getColumnListing('ngo_groups');
        $ngos = array_map(
            fn($ngo) => array_intersect_key($ngo, array_flip($existingColumns)),
            $ngos
        );

        NgoGroup::insert($ngos);
    }
}
