name: Trigger auto deployment for likaslens-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/likaslens-backend-AutoDeployTrigger-03d66e26-917e-4e72-b9d3-b716a27a2988.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LIKASLENSBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LIKASLENSBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LIKASLENSBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/apps/backend
          registryUrl: likaslensregistry.azurecr.io
          registryUsername: ${{ secrets.LIKASLENSBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LIKASLENSBACKEND_REGISTRY_PASSWORD }}
          containerAppName: likaslens-backend
          resourceGroup: likaslens
          imageToBuild: likaslensregistry.azurecr.io/likaslens-backend:${{ github.sha }}


